# -*- coding: utf-8 -*-
"""dataCleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E8os-B9lIvPOa6nHHCFJiQ_0-OyN69tZ
"""

import pandas as pd
import numpy as np

try:
    df = pd.read_csv("/content/top_10000_1960-now.csv", encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv("/content/top_10000_1960-now.csv", encoding='latin1')

print(df)

print("Shape of Dataset: ", df.shape) # (9999, 35)
features = df.columns
print("Features: ", features)

# Drop columns a bit with a lot of NaN values that don't matter for now.
df.drop(columns = ['Track URI', 'Album Artist URI(s)', 'Album Genres', 'Track Preview URL', 'Album Image URL', 'Copyrights', 'Artist Genres'], inplace = True)

print(df.isna().sum())
# There are 50 NaN values for "in_shazam_charts" and 95 NaN for "key". Will drop these rows

df = df.dropna()

columns = ['Track Duration (ms)', 'Tempo', 'Time Signature', 'Danceability', 'Energy', 'Loudness', 'Speechiness', 'Acousticness', 'Instrumentalness', 'Liveness', 'Valence']
zero_counts = df[columns].eq(0).sum()
print(zero_counts)

zero_columns = ['Track Duration (ms)', 'Tempo', 'Time Signature', 'Danceability', 'Energy', 'Loudness', 'Speechiness', 'Acousticness', 'Liveness', 'Valence']
mask = df[zero_columns].eq(0).any(axis = 1)
df = df[~mask]
zero_counts = df[columns].eq(0).sum()

mean_instr = df['Instrumentalness'].mean()
print(mean_instr)
df['Instrumentalness'] = df['Instrumentalness'].replace(0, mean_instr)

## Cleaning second dataset
try:
    df2 = pd.read_csv("/content/dataset.csv", encoding='utf-8')
except UnicodeDecodeError:
    df2 = pd.read_csv("/content/dataset.csv", encoding='latin1')

print(df2)

print("Shape of Dataset: ", df2.shape) # (9999, 35)
features2 = df2.columns
print("Features: ", features2)

df2 = df2[df2[['Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37',
       'Unnamed: 38']].isna().all(axis = 1)]
print(df2)

print(df2.isna().sum())

df2 = df2.drop(columns = ['Unnamed: 0', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37',
       'Unnamed: 38'])

columns2 = ['release_date', 'len', 'dating', 'violence', 'world/life', 'night/time',
       'shake_the_audience', 'family/gospel', 'romantic', 'communication',
       'obscene', 'music', 'movement/places', 'light/visual_perceptions',
       'family/spirtual', 'like/girls', 'sadness', 'feelings', 'danceability',
       'loudness', 'acousticness', 'instrumentalness', 'valence', 'energy']

mean2_instr = df2['instrumentalness'].mean()
print(mean2_instr)
df2['instrumentalness'] = df2['instrumentalness'].replace(0, mean2_instr)

zero_columns2 = ['loudness', 'valence', 'energy']
mask2 = df2[zero_columns2].eq(0).any(axis = 1)
df2 = df2[~mask2]